env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  project: './tsconfig.eslint.json'
plugins:
  - '@typescript-eslint'
rules:
  'complexity':
    - error
    - 10
