codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: '70...100'
  status:
    project:
      number: auto
      threshold: 10%
      informational: true
    patch:
      number: auto
      threshold: 10%
      informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,files'
  behavior: new
  require_changes: no
